# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/manim_scirpts',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/manim_scirpts',
                'lib_path': 'manim_scirpts'},
  'syms': {'manim_scirpts.core': {'manim_scirpts.core.foo': ('core.html#foo', 'manim_scirpts/core.py')}}}
